if(HELLO_TOOLCHAIN_INCLUDED)
  return()
endif()
set(HELLO_TOOLCHAIN_INCLUDED TRUE)

message("[debug] calling toolchain file: ${CMAKE_CURRENT_LIST_FILE} ${CMAKE_TOOLCHAIN_FILE}")
message("[debug] OHOS_SDK_NATIVE_PATH: ${OHOS_SDK_NATIVE_PATH}")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x64)