/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class droid_HelloWorld */

#ifndef _Included_droid_HelloWorld
#define _Included_droid_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     droid_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_droid_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
