
set(JPEGTURBO_ROOT "/home/zz/soft/libjpeg-turbo")
set(JPEGTURBO_INCLUDE_DIR "${JPEGTURBO_ROOT}/include")
set(JPEGTURBO_LIBRARY_DIR "${JPEGTURBO_ROOT}/lib")
set(JPEGTURBO_BINARY_DIR "${JPEGTURBO_ROOT}/bin")

if(JPEGTURBO_USE_STATIC_LIBS)
    add_library(JPEGTURBO::JPEGTURBO STATIC IMPORTED)
    set_target_properties(JPEGTURBO::JPEGTURBO PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${JPEGTURBO_INCLUDE_DIR}"
        IMPORTED_LOCATION "${JPEGTURBO_LIBRARY_DIR}/libturbojpeg.a"
    )
else()
    add_library(JPEGTURBO::JPEGTURBO SHARED IMPORTED)
    set_target_properties(JPEGTURBO::JPEGTURBO PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${JPEGTURBO_INCLUDE_DIR}"
        IMPORTED_LOCATION "${JPEGTURBO_LIBRARY_DIR}/libturbojpeg.so"
    )
endif()


#include(FindPackageHandleStandardArgs)
#find_package_handle_standard_args(JPEGTURBO REQUIRED_VARS JPEGTURBO_LIBRARY JPEGTURBO_INCLUDE_DIR)
